/**
 * This file was auto-generated by openapi-typescript.
 * Do not make direct changes to the file.
 */

export interface paths {
    "/api/health": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Health Endpoint */
        get: operations["health_endpoint_api_health_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/admin/rescan": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Rescan Endpoint */
        post: operations["rescan_endpoint_api_admin_rescan_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/projects": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** List Projects Endpoint */
        get: operations["list_projects_endpoint_api_projects_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/sessions": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** List Sessions Endpoint */
        get: operations["list_sessions_endpoint_api_sessions_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/sessions/{session_id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Get Session Endpoint */
        get: operations["get_session_endpoint_api_sessions__session_id__get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/sessions/{session_id}/pin": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Pin Session */
        post: operations["pin_session_api_sessions__session_id__pin_post"];
        /** Unpin Session */
        delete: operations["unpin_session_api_sessions__session_id__pin_delete"];
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/tags": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** List Tags Endpoint */
        get: operations["list_tags_endpoint_api_tags_get"];
        put?: never;
        /** Create Tag Endpoint */
        post: operations["create_tag_endpoint_api_tags_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/sessions/{session_id}/tags": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Attach Tag Endpoint */
        post: operations["attach_tag_endpoint_api_sessions__session_id__tags_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/sessions/{session_id}/tags/{tag_id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        post?: never;
        /** Detach Tag Endpoint */
        delete: operations["detach_tag_endpoint_api_sessions__session_id__tags__tag_id__delete"];
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/sessions/{session_id}/notes": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** List Notes Endpoint */
        get: operations["list_notes_endpoint_api_sessions__session_id__notes_get"];
        put?: never;
        /** Create Note Endpoint */
        post: operations["create_note_endpoint_api_sessions__session_id__notes_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/notes/{note_id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        post?: never;
        /** Delete Note Endpoint */
        delete: operations["delete_note_endpoint_api_notes__note_id__delete"];
        options?: never;
        head?: never;
        /** Update Note Endpoint */
        patch: operations["update_note_endpoint_api_notes__note_id__patch"];
        trace?: never;
    };
}
export type webhooks = Record<string, never>;
export interface components {
    schemas: {
        /** AttachTagRequest */
        AttachTagRequest: {
            /** Tag Id */
            tag_id?: number | null;
            /** Name */
            name?: string | null;
        };
        /** CreateNoteRequest */
        CreateNoteRequest: {
            /** Body */
            body: string;
        };
        /** CreateTagRequest */
        CreateTagRequest: {
            /** Name */
            name: string;
            /** Color */
            color?: string | null;
        };
        /** HTTPValidationError */
        HTTPValidationError: {
            /** Detail */
            detail?: components["schemas"]["ValidationError"][];
        };
        /** HealthResponse */
        HealthResponse: {
            /** Status */
            status: string;
            /** Db Path */
            db_path: string;
            /** Indexed Sessions */
            indexed_sessions: number;
        };
        /**
         * MessageItem
         * @description A single jsonl line, normalised into a UI-friendly shape.
         */
        MessageItem: {
            /** Uuid */
            uuid?: string | null;
            /** Parent Uuid */
            parent_uuid?: string | null;
            /** Timestamp */
            timestamp?: string | null;
            /** Type */
            type: string;
            /** Role */
            role?: string | null;
            /** Text */
            text?: string | null;
            /** Content */
            content?: {
                [key: string]: unknown;
            }[] | null;
            /** Tool Use */
            tool_use?: {
                [key: string]: unknown;
            }[] | null;
            /** Cwd */
            cwd?: string | null;
            /** Git Branch */
            git_branch?: string | null;
            /** Cc Version */
            cc_version?: string | null;
            /** Raw */
            raw?: {
                [key: string]: unknown;
            } | null;
        };
        /** NoteRow */
        NoteRow: {
            /** Note Id */
            note_id: number;
            /** Session Id */
            session_id: string;
            /** Body */
            body: string;
            /** Created At */
            created_at: string;
            /** Updated At */
            updated_at: string;
        };
        /** ProjectListItem */
        ProjectListItem: {
            /** Project Id */
            project_id: string;
            /** Decoded Cwd */
            decoded_cwd: string;
            /** Cwd Exists */
            cwd_exists: boolean;
            /** Session Count */
            session_count: number;
            /** Last Active At */
            last_active_at: string;
        };
        /** RescanRequest */
        RescanRequest: {
            /** Project Id */
            project_id?: string | null;
        };
        /** RescanResponse */
        RescanResponse: {
            /** Scanned Projects */
            scanned_projects: number;
            /** Scanned Sessions */
            scanned_sessions: number;
            /** Skipped Sessions */
            skipped_sessions: number;
            /** Elapsed Ms */
            elapsed_ms: number;
        };
        /** SessionDetailResponse */
        SessionDetailResponse: {
            session: components["schemas"]["SessionListItem"];
            /** Messages */
            messages: components["schemas"]["MessageItem"][];
            /** Has More */
            has_more: boolean;
            /**
             * Next Offset
             * @description line offset to pass next time
             * @default 0
             */
            next_offset: number;
        };
        /** SessionListItem */
        SessionListItem: {
            /** Session Id */
            session_id: string;
            /** Project Id */
            project_id: string;
            /** Decoded Cwd */
            decoded_cwd: string;
            /** Started At */
            started_at: string;
            /** Last Message At */
            last_message_at: string;
            /** Message Count */
            message_count: number;
            /** User Message Count */
            user_message_count: number;
            /** Assistant Message Count */
            assistant_message_count: number;
            /** Tool Use Count */
            tool_use_count: number;
            /** Subagent Count */
            subagent_count: number;
            /** Summary */
            summary: string | null;
            /** Git Branch */
            git_branch: string | null;
            /** Cc Version */
            cc_version: string | null;
            /** Pinned */
            pinned: boolean;
            /** Tags */
            tags: string[];
        };
        /** SessionListResponse */
        SessionListResponse: {
            /** Items */
            items: components["schemas"]["SessionListItem"][];
            /** Next Cursor */
            next_cursor?: string | null;
        };
        /** TagListItem */
        TagListItem: {
            /** Tag Id */
            tag_id: number;
            /** Name */
            name: string;
            /** Color */
            color: string | null;
            /** Session Count */
            session_count: number;
        };
        /** TagRow */
        TagRow: {
            /** Tag Id */
            tag_id: number;
            /** Name */
            name: string;
            /** Color */
            color?: string | null;
            /** Created At */
            created_at: string;
        };
        /** UpdateNoteRequest */
        UpdateNoteRequest: {
            /** Body */
            body: string;
        };
        /** ValidationError */
        ValidationError: {
            /** Location */
            loc: (string | number)[];
            /** Message */
            msg: string;
            /** Error Type */
            type: string;
            /** Input */
            input?: unknown;
            /** Context */
            ctx?: Record<string, never>;
        };
    };
    responses: never;
    parameters: never;
    requestBodies: never;
    headers: never;
    pathItems: never;
}
export type $defs = Record<string, never>;
export interface operations {
    health_endpoint_api_health_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HealthResponse"];
                };
            };
        };
    };
    rescan_endpoint_api_admin_rescan_post: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: {
            content: {
                "application/json": components["schemas"]["RescanRequest"] | null;
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["RescanResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    list_projects_endpoint_api_projects_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ProjectListItem"][];
                };
            };
        };
    };
    list_sessions_endpoint_api_sessions_get: {
        parameters: {
            query?: {
                project_id?: string | null;
                from?: string | null;
                to?: string | null;
                pinned?: boolean | null;
                tag?: string | null;
                limit?: number;
                cursor?: string | null;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["SessionListResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    get_session_endpoint_api_sessions__session_id__get: {
        parameters: {
            query?: {
                /** @description line offset to start from */
                offset?: number;
                limit?: number;
            };
            header?: never;
            path: {
                session_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["SessionDetailResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    pin_session_api_sessions__session_id__pin_post: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                session_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            204: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    unpin_session_api_sessions__session_id__pin_delete: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                session_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            204: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    list_tags_endpoint_api_tags_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["TagListItem"][];
                };
            };
        };
    };
    create_tag_endpoint_api_tags_post: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["CreateTagRequest"];
            };
        };
        responses: {
            /** @description Successful Response */
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["TagRow"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    attach_tag_endpoint_api_sessions__session_id__tags_post: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                session_id: string;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["AttachTagRequest"];
            };
        };
        responses: {
            /** @description Successful Response */
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["TagRow"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    detach_tag_endpoint_api_sessions__session_id__tags__tag_id__delete: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                session_id: string;
                tag_id: number;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            204: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    list_notes_endpoint_api_sessions__session_id__notes_get: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                session_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["NoteRow"][];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    create_note_endpoint_api_sessions__session_id__notes_post: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                session_id: string;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["CreateNoteRequest"];
            };
        };
        responses: {
            /** @description Successful Response */
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["NoteRow"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    delete_note_endpoint_api_notes__note_id__delete: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                note_id: number;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            204: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    update_note_endpoint_api_notes__note_id__patch: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                note_id: number;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["UpdateNoteRequest"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["NoteRow"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
}
