/**
 * This file was auto-generated by openapi-typescript.
 * Do not make direct changes to the file.
 */

export interface paths {
    "/api/health": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Health Endpoint */
        get: operations["health_endpoint_api_health_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/admin/rescan": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Rescan Endpoint */
        post: operations["rescan_endpoint_api_admin_rescan_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/projects": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** List Projects Endpoint */
        get: operations["list_projects_endpoint_api_projects_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/sessions": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** List Sessions Endpoint */
        get: operations["list_sessions_endpoint_api_sessions_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/sessions/{session_id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Get Session Endpoint */
        get: operations["get_session_endpoint_api_sessions__session_id__get"];
        put?: never;
        post?: never;
        /**
         * Delete Session Endpoint
         * @description overlay DB 의 세션 흔적만 삭제. ~/.claude/ 는 절대 건드리지 않는다.
         */
        delete: operations["delete_session_endpoint_api_sessions__session_id__delete"];
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/sessions/{session_id}/pin": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Pin Session */
        post: operations["pin_session_api_sessions__session_id__pin_post"];
        /** Unpin Session */
        delete: operations["unpin_session_api_sessions__session_id__pin_delete"];
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/tags": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** List Tags Endpoint */
        get: operations["list_tags_endpoint_api_tags_get"];
        put?: never;
        /** Create Tag Endpoint */
        post: operations["create_tag_endpoint_api_tags_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/sessions/{session_id}/tags": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Attach Tag Endpoint */
        post: operations["attach_tag_endpoint_api_sessions__session_id__tags_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/sessions/{session_id}/tags/{tag_id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        post?: never;
        /** Detach Tag Endpoint */
        delete: operations["detach_tag_endpoint_api_sessions__session_id__tags__tag_id__delete"];
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/sessions/{session_id}/notes": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** List Notes Endpoint */
        get: operations["list_notes_endpoint_api_sessions__session_id__notes_get"];
        put?: never;
        /** Create Note Endpoint */
        post: operations["create_note_endpoint_api_sessions__session_id__notes_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/notes/{note_id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        post?: never;
        /** Delete Note Endpoint */
        delete: operations["delete_note_endpoint_api_notes__note_id__delete"];
        options?: never;
        head?: never;
        /** Update Note Endpoint */
        patch: operations["update_note_endpoint_api_notes__note_id__patch"];
        trace?: never;
    };
    "/api/sessions/{session_id}/highlights": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** List Highlights Endpoint */
        get: operations["list_highlights_endpoint_api_sessions__session_id__highlights_get"];
        put?: never;
        /** Create Highlight Endpoint */
        post: operations["create_highlight_endpoint_api_sessions__session_id__highlights_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/highlights/{highlight_id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        post?: never;
        /** Delete Highlight Endpoint */
        delete: operations["delete_highlight_endpoint_api_highlights__highlight_id__delete"];
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/artifacts/paths": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** List Artifact Paths Endpoint */
        get: operations["list_artifact_paths_endpoint_api_artifacts_paths_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/artifacts/sessions": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** List Artifact Path Sessions Endpoint */
        get: operations["list_artifact_path_sessions_endpoint_api_artifacts_sessions_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/search": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Search Endpoint
         * @description FTS5 search across session summaries, file paths, and project paths.
         */
        get: operations["search_endpoint_api_search_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/housekeeping/scan": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Scan Endpoint */
        get: operations["scan_endpoint_api_housekeeping_scan_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/knowledge": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** List Knowledge Endpoint */
        get: operations["list_knowledge_endpoint_api_knowledge_get"];
        put?: never;
        /** Create Knowledge Endpoint */
        post: operations["create_knowledge_endpoint_api_knowledge_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/knowledge/{knowledge_id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Get Knowledge Endpoint */
        get: operations["get_knowledge_endpoint_api_knowledge__knowledge_id__get"];
        put?: never;
        post?: never;
        /** Delete Knowledge Endpoint */
        delete: operations["delete_knowledge_endpoint_api_knowledge__knowledge_id__delete"];
        options?: never;
        head?: never;
        /** Update Knowledge Endpoint */
        patch: operations["update_knowledge_endpoint_api_knowledge__knowledge_id__patch"];
        trace?: never;
    };
    "/api/knowledge/{knowledge_id}/links": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Create Link Endpoint */
        post: operations["create_link_endpoint_api_knowledge__knowledge_id__links_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/knowledge/links/{link_id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        post?: never;
        /** Delete Link Endpoint */
        delete: operations["delete_link_endpoint_api_knowledge_links__link_id__delete"];
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/knowledge/from-highlight": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Promote Highlight Endpoint */
        post: operations["promote_highlight_endpoint_api_knowledge_from_highlight_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
}
export type webhooks = Record<string, never>;
export interface components {
    schemas: {
        /**
         * ArtifactPathItem
         * @description /artifacts 카탈로그의 한 행 — 1 path = 1 항목.
         */
        ArtifactPathItem: {
            /** Path */
            path: string;
            /** Last Modified */
            last_modified: string;
            /** Edit Count */
            edit_count: number;
            /** Session Count */
            session_count: number;
            /** Tools */
            tools: string[];
            /** Last Session Id */
            last_session_id: string;
            /** Last Session Summary */
            last_session_summary?: string | null;
            /** Exists */
            exists: boolean;
        };
        /** ArtifactPathListResponse */
        ArtifactPathListResponse: {
            /** Items */
            items: components["schemas"]["ArtifactPathItem"][];
            /** Next Offset */
            next_offset?: number | null;
        };
        /**
         * ArtifactSessionRef
         * @description 특정 path 를 건드린 한 세션 요약 (path 역참조 drawer).
         */
        ArtifactSessionRef: {
            /** Session Id */
            session_id: string;
            /** Session Summary */
            session_summary?: string | null;
            /** Decoded Cwd */
            decoded_cwd?: string | null;
            /** Tool Name */
            tool_name: string;
            /** Message Uuid */
            message_uuid?: string | null;
            /** Created At */
            created_at: string;
            /** Edit Count */
            edit_count: number;
        };
        /** AttachTagRequest */
        AttachTagRequest: {
            /** Tag Id */
            tag_id?: number | null;
            /** Name */
            name?: string | null;
        };
        /** CreateHighlightRequest */
        CreateHighlightRequest: {
            /** Message Uuid */
            message_uuid?: string | null;
            /** Text */
            text: string;
            /**
             * Kind
             * @default insight
             */
            kind: string;
        };
        /** CreateKnowledgeRequest */
        CreateKnowledgeRequest: {
            /** Title */
            title: string;
            /**
             * Body
             * @default
             */
            body: string;
            /**
             * Kind
             * @default insight
             * @enum {string}
             */
            kind: "prompt" | "recipe" | "snippet" | "insight" | "question";
            /** Source Type */
            source_type?: ("knowledge" | "session" | "highlight" | "note") | null;
            /** Source Id */
            source_id?: string | null;
        };
        /** CreateLinkRequest */
        CreateLinkRequest: {
            /**
             * From Type
             * @enum {string}
             */
            from_type: "knowledge" | "session" | "highlight" | "note";
            /** From Id */
            from_id: string;
            /**
             * To Type
             * @enum {string}
             */
            to_type: "knowledge" | "session" | "highlight" | "note";
            /** To Id */
            to_id: string;
            /**
             * Relation
             * @default related
             * @enum {string}
             */
            relation: "related" | "derives_from" | "refines" | "contradicts";
        };
        /** CreateNoteRequest */
        CreateNoteRequest: {
            /** Body */
            body: string;
        };
        /** CreateTagRequest */
        CreateTagRequest: {
            /** Name */
            name: string;
            /** Color */
            color?: string | null;
        };
        /** HTTPValidationError */
        HTTPValidationError: {
            /** Detail */
            detail?: components["schemas"]["ValidationError"][];
        };
        /** HealthResponse */
        HealthResponse: {
            /** Status */
            status: string;
            /** Db Path */
            db_path: string;
            /** Indexed Sessions */
            indexed_sessions: number;
        };
        /**
         * HighlightRow
         * @description 세션 메시지에서 사용자가 선택·저장한 텍스트 인용.
         */
        HighlightRow: {
            /** Highlight Id */
            highlight_id: number;
            /** Session Id */
            session_id: string;
            /** Message Uuid */
            message_uuid?: string | null;
            /** Text */
            text: string;
            /** Kind */
            kind: string;
            /** Created At */
            created_at: string;
        };
        /** HousekeepingCandidateItem */
        HousekeepingCandidateItem: {
            /**
             * Category
             * @enum {string}
             */
            category: "stale_session" | "empty_project" | "orphan_project" | "orphan_session";
            /** Entity Id */
            entity_id: string;
            /** Display Name */
            display_name: string;
            /** Reason */
            reason: string;
            /** Size Bytes */
            size_bytes?: number | null;
            /** Last Activity */
            last_activity?: string | null;
            /** Metadata */
            metadata?: {
                [key: string]: unknown;
            };
        };
        /** HousekeepingScanResponse */
        HousekeepingScanResponse: {
            /** Items */
            items: components["schemas"]["HousekeepingCandidateItem"][];
            /** Scanned At */
            scanned_at: string;
            /** Summary */
            summary: {
                [key: string]: number;
            };
            /** Total Size Bytes */
            total_size_bytes: number;
        };
        /** KnowledgeDetailResponse */
        KnowledgeDetailResponse: {
            item: components["schemas"]["KnowledgeRow"];
            /** Links */
            links?: components["schemas"]["KnowledgeLinkRow"][];
            /** Backlinks */
            backlinks?: components["schemas"]["KnowledgeLinkRow"][];
        };
        /** KnowledgeLinkRow */
        KnowledgeLinkRow: {
            /** Link Id */
            link_id: number;
            /**
             * From Type
             * @enum {string}
             */
            from_type: "knowledge" | "session" | "highlight" | "note";
            /** From Id */
            from_id: string;
            /**
             * To Type
             * @enum {string}
             */
            to_type: "knowledge" | "session" | "highlight" | "note";
            /** To Id */
            to_id: string;
            /**
             * Relation
             * @default related
             * @enum {string}
             */
            relation: "related" | "derives_from" | "refines" | "contradicts";
            /** Created At */
            created_at: string;
        };
        /** KnowledgeListResponse */
        KnowledgeListResponse: {
            /** Items */
            items: components["schemas"]["KnowledgeRow"][];
            /** Total Count */
            total_count: number;
            /** Next Offset */
            next_offset?: number | null;
        };
        /** KnowledgeRow */
        KnowledgeRow: {
            /** Knowledge Id */
            knowledge_id: number;
            /** Title */
            title: string;
            /**
             * Body
             * @default
             */
            body: string;
            /**
             * Kind
             * @default insight
             * @enum {string}
             */
            kind: "prompt" | "recipe" | "snippet" | "insight" | "question";
            /** Source Type */
            source_type?: ("knowledge" | "session" | "highlight" | "note") | null;
            /** Source Id */
            source_id?: string | null;
            /** Created At */
            created_at: string;
            /** Updated At */
            updated_at: string;
        };
        /**
         * MessageItem
         * @description A single jsonl line, normalised into a UI-friendly shape.
         */
        MessageItem: {
            /** Uuid */
            uuid?: string | null;
            /** Parent Uuid */
            parent_uuid?: string | null;
            /** Timestamp */
            timestamp?: string | null;
            /** Type */
            type: string;
            /** Role */
            role?: string | null;
            /** Text */
            text?: string | null;
            /** Content */
            content?: {
                [key: string]: unknown;
            }[] | null;
            /** Tool Use */
            tool_use?: {
                [key: string]: unknown;
            }[] | null;
            /** Cwd */
            cwd?: string | null;
            /** Git Branch */
            git_branch?: string | null;
            /** Cc Version */
            cc_version?: string | null;
            /** Raw */
            raw?: {
                [key: string]: unknown;
            } | null;
        };
        /** NoteRow */
        NoteRow: {
            /** Note Id */
            note_id: number;
            /** Session Id */
            session_id: string;
            /** Body */
            body: string;
            /** Created At */
            created_at: string;
            /** Updated At */
            updated_at: string;
        };
        /** ProjectListItem */
        ProjectListItem: {
            /** Project Id */
            project_id: string;
            /** Decoded Cwd */
            decoded_cwd: string;
            /** Cwd Exists */
            cwd_exists: boolean;
            /** Session Count */
            session_count: number;
            /** Last Active At */
            last_active_at: string;
        };
        /** PromoteHighlightRequest */
        PromoteHighlightRequest: {
            /** Highlight Id */
            highlight_id: number;
            /** Title */
            title?: string | null;
            /**
             * Kind
             * @default insight
             * @enum {string}
             */
            kind: "prompt" | "recipe" | "snippet" | "insight" | "question";
        };
        /** RescanRequest */
        RescanRequest: {
            /** Project Id */
            project_id?: string | null;
        };
        /** RescanResponse */
        RescanResponse: {
            /** Scanned Projects */
            scanned_projects: number;
            /** Scanned Sessions */
            scanned_sessions: number;
            /** Skipped Sessions */
            skipped_sessions: number;
            /** Elapsed Ms */
            elapsed_ms: number;
        };
        /** SearchResponse */
        SearchResponse: {
            /** Items */
            items: components["schemas"]["SessionListItem"][];
            /** Query */
            query: string;
        };
        /** SessionDetailResponse */
        SessionDetailResponse: {
            session: components["schemas"]["SessionListItem"];
            /** Messages */
            messages: components["schemas"]["MessageItem"][];
            /** Has More */
            has_more: boolean;
            /**
             * Next Offset
             * @description line offset to pass next time
             * @default 0
             */
            next_offset: number;
            /**
             * Total Lines
             * @description total valid message lines in jsonl
             * @default 0
             */
            total_lines: number;
        };
        /** SessionListItem */
        SessionListItem: {
            /** Session Id */
            session_id: string;
            /** Project Id */
            project_id: string;
            /** Decoded Cwd */
            decoded_cwd: string;
            /** Started At */
            started_at: string;
            /** Last Message At */
            last_message_at: string;
            /** Message Count */
            message_count: number;
            /** User Message Count */
            user_message_count: number;
            /** Assistant Message Count */
            assistant_message_count: number;
            /** Tool Use Count */
            tool_use_count: number;
            /** Subagent Count */
            subagent_count: number;
            /** Summary */
            summary: string | null;
            /** Git Branch */
            git_branch: string | null;
            /** Cc Version */
            cc_version: string | null;
            /** Pinned */
            pinned: boolean;
            /** Tags */
            tags: string[];
        };
        /** SessionListResponse */
        SessionListResponse: {
            /** Items */
            items: components["schemas"]["SessionListItem"][];
            /** Next Cursor */
            next_cursor?: string | null;
        };
        /** TagListItem */
        TagListItem: {
            /** Tag Id */
            tag_id: number;
            /** Name */
            name: string;
            /** Color */
            color: string | null;
            /** Session Count */
            session_count: number;
        };
        /** TagRow */
        TagRow: {
            /** Tag Id */
            tag_id: number;
            /** Name */
            name: string;
            /** Color */
            color?: string | null;
            /** Created At */
            created_at: string;
        };
        /** UpdateKnowledgeRequest */
        UpdateKnowledgeRequest: {
            /** Title */
            title?: string | null;
            /** Body */
            body?: string | null;
            /** Kind */
            kind?: ("prompt" | "recipe" | "snippet" | "insight" | "question") | null;
        };
        /** UpdateNoteRequest */
        UpdateNoteRequest: {
            /** Body */
            body: string;
        };
        /** ValidationError */
        ValidationError: {
            /** Location */
            loc: (string | number)[];
            /** Message */
            msg: string;
            /** Error Type */
            type: string;
            /** Input */
            input?: unknown;
            /** Context */
            ctx?: Record<string, never>;
        };
    };
    responses: never;
    parameters: never;
    requestBodies: never;
    headers: never;
    pathItems: never;
}
export type $defs = Record<string, never>;
export interface operations {
    health_endpoint_api_health_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HealthResponse"];
                };
            };
        };
    };
    rescan_endpoint_api_admin_rescan_post: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: {
            content: {
                "application/json": components["schemas"]["RescanRequest"] | null;
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["RescanResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    list_projects_endpoint_api_projects_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ProjectListItem"][];
                };
            };
        };
    };
    list_sessions_endpoint_api_sessions_get: {
        parameters: {
            query?: {
                project_id?: string | null;
                from?: string | null;
                to?: string | null;
                pinned?: boolean | null;
                tag?: string | null;
                limit?: number;
                cursor?: string | null;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["SessionListResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    get_session_endpoint_api_sessions__session_id__get: {
        parameters: {
            query?: {
                /** @description line offset to start from */
                offset?: number;
                limit?: number;
                /** @description true 면 최신 메시지부터 역순 로딩 */
                from_end?: boolean;
            };
            header?: never;
            path: {
                session_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["SessionDetailResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    delete_session_endpoint_api_sessions__session_id__delete: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                session_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            204: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    pin_session_api_sessions__session_id__pin_post: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                session_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            204: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    unpin_session_api_sessions__session_id__pin_delete: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                session_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            204: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    list_tags_endpoint_api_tags_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["TagListItem"][];
                };
            };
        };
    };
    create_tag_endpoint_api_tags_post: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["CreateTagRequest"];
            };
        };
        responses: {
            /** @description Successful Response */
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["TagRow"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    attach_tag_endpoint_api_sessions__session_id__tags_post: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                session_id: string;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["AttachTagRequest"];
            };
        };
        responses: {
            /** @description Successful Response */
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["TagRow"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    detach_tag_endpoint_api_sessions__session_id__tags__tag_id__delete: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                session_id: string;
                tag_id: number;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            204: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    list_notes_endpoint_api_sessions__session_id__notes_get: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                session_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["NoteRow"][];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    create_note_endpoint_api_sessions__session_id__notes_post: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                session_id: string;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["CreateNoteRequest"];
            };
        };
        responses: {
            /** @description Successful Response */
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["NoteRow"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    delete_note_endpoint_api_notes__note_id__delete: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                note_id: number;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            204: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    update_note_endpoint_api_notes__note_id__patch: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                note_id: number;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["UpdateNoteRequest"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["NoteRow"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    list_highlights_endpoint_api_sessions__session_id__highlights_get: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                session_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HighlightRow"][];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    create_highlight_endpoint_api_sessions__session_id__highlights_post: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                session_id: string;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["CreateHighlightRequest"];
            };
        };
        responses: {
            /** @description Successful Response */
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HighlightRow"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    delete_highlight_endpoint_api_highlights__highlight_id__delete: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                highlight_id: number;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            204: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    list_artifact_paths_endpoint_api_artifacts_paths_get: {
        parameters: {
            query?: {
                limit?: number;
                offset?: number;
                /** @description path substring (LIKE) */
                q?: string | null;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ArtifactPathListResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    list_artifact_path_sessions_endpoint_api_artifacts_sessions_get: {
        parameters: {
            query: {
                /** @description 파일 전체 경로 (path 역참조) */
                path: string;
                limit?: number;
                offset?: number;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ArtifactSessionRef"][];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    search_endpoint_api_search_get: {
        parameters: {
            query: {
                /** @description Search query */
                q: string;
                limit?: number;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["SearchResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    scan_endpoint_api_housekeeping_scan_get: {
        parameters: {
            query?: {
                stale_days?: number;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HousekeepingScanResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    list_knowledge_endpoint_api_knowledge_get: {
        parameters: {
            query?: {
                kind?: string | null;
                q?: string | null;
                limit?: number;
                offset?: number;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["KnowledgeListResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    create_knowledge_endpoint_api_knowledge_post: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["CreateKnowledgeRequest"];
            };
        };
        responses: {
            /** @description Successful Response */
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["KnowledgeRow"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    get_knowledge_endpoint_api_knowledge__knowledge_id__get: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                knowledge_id: number;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["KnowledgeDetailResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    delete_knowledge_endpoint_api_knowledge__knowledge_id__delete: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                knowledge_id: number;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            204: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    update_knowledge_endpoint_api_knowledge__knowledge_id__patch: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                knowledge_id: number;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["UpdateKnowledgeRequest"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["KnowledgeRow"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    create_link_endpoint_api_knowledge__knowledge_id__links_post: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                knowledge_id: number;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["CreateLinkRequest"];
            };
        };
        responses: {
            /** @description Successful Response */
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["KnowledgeLinkRow"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    delete_link_endpoint_api_knowledge_links__link_id__delete: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                link_id: number;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            204: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    promote_highlight_endpoint_api_knowledge_from_highlight_post: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["PromoteHighlightRequest"];
            };
        };
        responses: {
            /** @description Successful Response */
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["KnowledgeRow"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
}
